SpecMgrs = DECLARE_MODULE("SpecialMgrs")

if not SpecMgrs.__RELOADING then
    SpecMgrs.http_mgr = require("Mgrs.Special.HttpMgr").New()
    SpecMgrs.download_mgr = require("Mgrs.Special.DownloadMgr").New()
    SpecMgrs.system_mgr = require("Mgrs.Special.SystemMgr").New()
    SpecMgrs.timer_mgr = require("CommonTypes.TimerMgr").New()
    SpecMgrs.event_mgr = require("Mgrs.Special.EventMgr").New()
    SpecMgrs.input_mgr = require("Mgrs.Special.InputMgr").New()
    SpecMgrs.msg_mgr = require("Mgrs.Special.MsgMgr").New()
    SpecMgrs.res_mgr = require("Mgrs.Special.ResMgr").New()
    SpecMgrs.effect_mgr = require("Mgrs.Special.EffectMgr").New()
    SpecMgrs.data_mgr = require("Mgrs.Special.DataMgr").New()
    SpecMgrs.config_mgr = require("Mgrs.Special.ConfigMgr").New()
    SpecMgrs.ui_mgr = require("Mgrs.Special.UIMgr").New()
    SpecMgrs.uianim_mgr = require("Mgrs.Special.UIAnimMgr").New()
    SpecMgrs.sound_mgr = require("Mgrs.Special.SoundMgr").New()
    SpecMgrs.stage_mgr = require("Mgrs.Special.StageMgr").New()
    SpecMgrs.camera_mgr = require("Mgrs.Special.CameraMgr").New()
    SpecMgrs.soldier_battle_mgr = require("Mgrs.Special.SoldierBattleMgr").New()
    SpecMgrs.hero_battle_mgr = require("Mgrs.Special.HeroBattleMgr").New()
    SpecMgrs.guide_mgr = require("Mgrs.Special.GuideMgr").New()
    SpecMgrs.redpoint_mgr = require("Mgrs.Special.RedPointMgr").New()
    SpecMgrs.sdk_mgr = require("Mgrs.Special.SDKMgr").New()
end

function SpecMgrs:DoInit()
    self.http_mgr:DoInit()
    self.download_mgr:DoInit()
    self.config_mgr:DoInit()
    self.system_mgr:DoInit()
    self.timer_mgr:DoInit()
    self.event_mgr:DoInit()
    self.input_mgr:DoInit()
    self.res_mgr:DoInit()
    self.effect_mgr:DoInit()
    self.msg_mgr:DoInit()
    self.ui_mgr:DoInit()
    self.uianim_mgr:DoInit()
    self.redpoint_mgr:DoInit()
    self.sound_mgr:DoInit()
    self.stage_mgr:DoInit()
    self.camera_mgr:DoInit()
    self.soldier_battle_mgr:DoInit()
    self.hero_battle_mgr:DoInit()
    self.guide_mgr:DoInit()
    self.sdk_mgr:DoInit()
end

function SpecMgrs:Update(delta_time)
    self.http_mgr:Update(delta_time)
    self.download_mgr:Update(delta_time)
    self.timer_mgr:Update(delta_time)
    self.event_mgr:Update(delta_time)
    self.input_mgr:Update(delta_time)
    self.effect_mgr:Update(delta_time)
    self.msg_mgr:Update(delta_time)
    self.ui_mgr:Update(delta_time)
    self.uianim_mgr:Update(delta_time)
    self.sound_mgr:Update(delta_time)
    self.stage_mgr:Update(delta_time)
    self.camera_mgr:Update(delta_time)
    self.soldier_battle_mgr:Update(delta_time)
    self.hero_battle_mgr:Update(delta_time)
    self.sdk_mgr.Update(delta_time)
end

function SpecMgrs:LateUpdate(delta_time)
end

function SpecMgrs:DoDestroy()
    self.guide_mgr:DoDestroy()
    self.http_mgr:DoDestroy()
    self.download_mgr:DoDestroy()
    self.stage_mgr:DoDestroy()
    self.sound_mgr:DoDestroy()
    self.input_mgr:DoDestroy()
    self.config_mgr:DoDestroy()
    self.ui_mgr:DoDestroy()
    self.redpoint_mgr:DoDestroy()
    self.uianim_mgr:DoDestroy()
    self.msg_mgr:DoDestroy()
    self.effect_mgr:DoDestroy()
    self.res_mgr:DoDestroy()
    self.event_mgr:DoDestroy()
    self.system_mgr:DoDestroy()
    self.camera_mgr:DoDestroy()
    self.soldier_battle_mgr:DoDestroy()
    self.hero_battle_mgr:DoDestroy()
    self.sdk_mgr:DoDestroy()
end